import Head from "next/head";
import Link from "next/link";

import { signIn, signOut, useSession } from "next-auth/react";
import Button from "~/components/Button";
import Heading from "~/components/Heading";

interface Props extends React.PropsWithChildren {
  title: string;
}

const BasicLayout = ({ title, children }: Props) => {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>{title} - Strava App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full px-10 pt-4">
        <div className="container">
          <nav>
            <Link href="/">Home</Link>
            <Link href="/activities">Activities</Link>
          </nav>

          <Button
            handleClick={
              sessionData ? () => void signOut() : () => void signIn("strava")
            }
          >
            {sessionData ? "Sign out" : "Sign in"}
          </Button>
        </div>
      </header>
      <main className="w-full p-10">
        <Heading as="h1">{title}</Heading>
        <div className="container">{children}</div>
      </main>

      {/* <footer className="w-full px-10 pt-4">
        {sessionData && (
          <p className="text-2xl">
            <span>Logged in as {sessionData.user?.name} </span>
          </p>
        )}
      </footer> */}
    </>
  );
};

export default BasicLayout;
