import Head from "next/head";

import { signIn,  useSession } from "next-auth/react";
import Button from "~/components/Button";
import Heading from "~/components/Heading";
import NavBar from "~/components/NavBar";

interface Props extends React.PropsWithChildren {
  title: string;
}

const BasicLayout = ({ title, children }: Props) => {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Strava App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <header className="w-full px-10 pt-4">
        <div className="container mx-auto">

        {!sessionData && (
          <Button
          handleClick={
            () => void signIn("strava")
          }
        >
          {"Sign in"}
        </Button>
        )}
          
        </div>
      </header>
      <main className="w-full p-10">
        <div className="container  mx-auto">
          <Heading as="h1">{title}</Heading>
          {children}
        </div>
      </main>
    </>
  );
};

export default BasicLayout;


