import Head from "next/head";

import Heading from "~/components/Heading";
import NavBar from "~/components/NavBar";

interface Props extends React.PropsWithChildren {
  title: string;
}

const BasicLayout = ({ title, children }: Props) => {
  return (
    <>
      <Head>
        <title>Strava App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/strava.svg" />
      </Head>
      <NavBar />

      <main className="w-full p-10">
        <div className="container  mx-auto  max-w-7xl px-2 sm:px-6 lg:px-8">
          <Heading as="h1">{title}</Heading>
          {children}
        </div>
      </main>
    </>
  );
};

export default BasicLayout;
