import { type NextPage } from "next";
import Head from "next/head";

import AuthShowcase from "~/components/AuthShowCase";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T3 Strava App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-full flex-col items-center justify-center bg-black px-2">
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;
